task:
  timeout_in: 120m
  freebsd_instance:
    matrix:
      - image_family: freebsd-13-0-snap

  env:
    ASSUME_ALWAYS_YES: YES
  setup_script:
    - pkg update -f
    - pkg install bash
    - pkg install cmake
    - pkg install git
  build_script:
    - ls /tmp/cirrus-ci-build/
    - mkdir build
    - cd build
    - cmake ..
    - ls /tmp/cirrus-ci-build/
    - ls /tmp/cirrus-ci-build/build/singleheader
    - /tmp/cirrus-ci-build/build/singleheader/amalgamate.sh
    - make VERBOSE=1
  test_script:
    - ctest  --extra-verbose