kind: pipeline
name: x64

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: gcc:8
  commands:
  - make
  - make quiettest
  - make amalgamate
---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: gcc:8
  commands:
  - make
  - make quiettest
  - make amalgamate
---
kind: pipeline
name: stylecheck

platform:
  os: linux
  arch: amd64

steps:
- name: Build and Test
  image: ubuntu:18.04
  commands:
    - apt-get update -y
    - apt-get install -y python clang-format
    - ./style/run-clang-format.py -r include/ benchmark/ src/ tests/
---
kind: pipeline
name: amd64_clang_cmake

platform:
  os: linux
  arch: amd64

steps:
- name: Build and Test
  image: ubuntu:18.04
  environment:
    CC: clang
    CXX: clang++
  commands:
    - apt-get update -y
    - apt-get install -y make $CC g++ cmake 
    - $CC --version
    - mkdir build && cd build
    - cmake $CMAKE_FLAGS ..
    - make -j
    - ctest
---
kind: pipeline
name: amd64_gcc_cmake

platform:
  os: linux
  arch: amd64

steps:
- name: Build and Test
  image: ubuntu:18.04
  environment:
    CC: gcc
    CXX: g++
  commands:
    - apt-get update -y
    - apt-get install -y make $CC g++ cmake 
    - $CC --version
    - mkdir build && cd build
    - cmake $CMAKE_FLAGS ..
    - make -j
    - ctest
---
kind: pipeline
name: arm64_clang_cmake

platform:
  os: linux
  arch: arm64

steps:
- name: Build and Test
  image: ubuntu:18.04
  environment:
    CC: clang
    CXX: clang++
  commands:
    - apt-get update -y
    - apt-get install -y make $CC g++ cmake 
    - $CC --version
    - mkdir build && cd build
    - cmake $CMAKE_FLAGS ..
    - make -j
    - ctest
---
kind: pipeline
name: arm64_gcc_cmake

platform:
  os: linux
  arch: arm64

steps:
- name: Build and Test
  image: ubuntu:18.04
  environment:
    CC: gcc
    CXX: g++
  commands:
    - apt-get update -y
    - apt-get install -y make $CC g++ cmake
    - $CC --version
    - mkdir build && cd build
    - cmake $CMAKE_FLAGS ..
    - make -j
    - ctest
