name: Ubuntu 18.04 CI (GCC 7)

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.0
        with:
          cmake-version: '3.9.x'
      - name: Use cmake
        run: |
          mkdir build &&
          cd build &&
          cmake -DCMAKE_INSTALL_PREFIX:PATH=destination ..  &&
          cmake --build -j -DSIMDJSON_GOOGLE_BENCHMARKS=ON -DSIMDJSON_BUILD_STATIC=ON  .  &&
          ctest  -j4 --output-on-failure .  &&
          make install  &&
          echo -e '#include <simdjson.h>\nint main(int argc,char**argv) {simdjson::dom::parser parser;simdjson::dom::element tweets = parser.load(argv[1]); }' > tmp.cpp && c++ -Ibuild/destination/include -Lbuild/destination/lib -std=c++17 -Wl,-rpath,build/destination/lib -o linkandrun tmp.cpp -lsimdjson && ./linkandrun jsonexamples/twitter.json
